Repository SeoHaeng/SeoHaeng_BE, pull requests merged in 2025-08, with the labels that each got.

#28 [Chore] 환경변수 로드 단계 전 배포용 폴더 생성
  .github/workflows/deploy-dev.yml
Labels: 🐛 bug

#29 [Chore] 환경설정 파일명 변경
  Dockerfile
  docker-compose.yml
  src/main/resources/application-local.yml
Labels: 🐛 bug

#30 [Chore] 도커 이미지 빌드 시 application.yml 포함하도록 수정
  .github/workflows/deploy-dev.yml
  Dockerfile
Labels: 🐛 bug

#31 [Chore] 도커 이미지 빌드 경로 수정
  .github/workflows/deploy-dev.yml
Labels: 🐛 bug

#35 ♻️[Refactor] API 응답 형식 수정 및 리팩토링
  src/main/java/com/seohaeng/backend/domain/bookChallenge/controller/BookChallengeController.java
  src/main/java/com/seohaeng/backend/domain/bookChallenge/converter/BookChallengeConverter.java
  src/main/java/com/seohaeng/backend/domain/bookChallenge/dto/BookChallengeRequestDTO.java
  src/main/java/com/seohaeng/backend/domain/bookChallenge/dto/BookChallengeResponseDTO.java
  src/main/java/com/seohaeng/backend/domain/bookChallenge/entity/BookChallenge.java
  src/main/java/com/seohaeng/backend/domain/bookChallenge/entity/BookChallengeProof.java
  src/main/java/com/seohaeng/backend/domain/bookChallenge/entity/BookChallengeProofImage.java
  src/main/java/com/seohaeng/backend/domain/bookChallenge/repository/BookChallengeRepository.java
  src/main/java/com/seohaeng/backend/domain/bookChallenge/service/BookChallengeCommandService.java
  src/main/java/com/seohaeng/backend/domain/bookChallenge/service/BookChallengeQueryService.java
  src/main/java/com/seohaeng/backend/domain/readingSpot/controller/ReadingSpotController.java
  src/main/java/com/seohaeng/backend/domain/readingSpot/converter/ReadingSpotConverter.java
  src/main/java/com/seohaeng/backend/domain/readingSpot/dto/ReadingSpotResponseDTO.java
  src/main/java/com/seohaeng/backend/domain/readingSpot/service/ReadingSpotQueryService.java
  src/main/java/com/seohaeng/backend/domain/user/controller/OwnerController.java
  src/main/java/com/seohaeng/backend/domain/user/controller/UserController.java
  src/main/java/com/seohaeng/backend/domain/user/converter/UserConverter.java
  src/main/java/com/seohaeng/backend/domain/user/dto/UserResponseDTO.java
  src/main/java/com/seohaeng/backend/domain/user/entity/Owner.java
  src/main/java/com/seohaeng/backend/domain/user/entity/User.java
  src/main/java/com/seohaeng/backend/domain/user/repository/UserRepository.java
  src/main/java/com/seohaeng/backend/domain/user/service/UserQueryService.java
  src/main/java/com/seohaeng/backend/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨ feature, ♻️ refactor

#36 ♻️[Refactor] 공간 책갈피 응답 형식, 생성 처리 로직 수정
  src/main/java/com/seohaeng/backend/domain/bookChallenge/converter/BookChallengeConverter.java
  src/main/java/com/seohaeng/backend/domain/bookChallenge/dto/BookChallengeRequestDTO.java
  src/main/java/com/seohaeng/backend/domain/bookChallenge/dto/BookChallengeResponseDTO.java
  src/main/java/com/seohaeng/backend/domain/bookChallenge/entity/BookChallenge.java
  src/main/java/com/seohaeng/backend/domain/bookChallenge/entity/BookChallengeProof.java
  src/main/java/com/seohaeng/backend/domain/bookChallenge/service/BookChallengeCommandService.java
  src/main/java/com/seohaeng/backend/domain/bookChallenge/service/BookChallengeQueryService.java
  src/main/java/com/seohaeng/backend/domain/place/service/AddressUtil.java
  src/main/java/com/seohaeng/backend/domain/readingSpot/controller/ReadingSpotController.java
  src/main/java/com/seohaeng/backend/domain/readingSpot/converter/ReadingSpotConverter.java
  src/main/java/com/seohaeng/backend/domain/readingSpot/dto/ReadingSpotResponseDTO.java
  src/main/java/com/seohaeng/backend/domain/readingSpot/entity/ReadingSpot.java
  src/main/java/com/seohaeng/backend/domain/readingSpot/service/ReadingSpotCommandService.java
  src/main/java/com/seohaeng/backend/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨ feature

#48 ✨[Feat] 시설 관련 API 추가, Tour Apir 데이터 파이프라인 구성
  src/main/java/com/seohaeng/backend/BackendApplication.java
  src/main/java/com/seohaeng/backend/domain/place/controller/PlaceController.java
  src/main/java/com/seohaeng/backend/domain/place/converter/PlaceConverter.java
  src/main/java/com/seohaeng/backend/domain/place/dto/PlaceResponseDTO.java
  src/main/java/com/seohaeng/backend/domain/place/dto/tourapiResponseDTO/AreaBasedSearchResponseDTO.java
  src/main/java/com/seohaeng/backend/domain/place/dto/tourapiResponseDTO/DetailCommonResponseDTO.java
  src/main/java/com/seohaeng/backend/domain/place/dto/tourapiResponseDTO/DetailIntroFestivalResponseDTO.java
  src/main/java/com/seohaeng/backend/domain/place/dto/tourapiResponseDTO/DetailIntroResponse.java
  src/main/java/com/seohaeng/backend/domain/place/dto/tourapiResponseDTO/DetailIntroRestaurantResponseDTO.java
  src/main/java/com/seohaeng/backend/domain/place/dto/tourapiResponseDTO/DetailIntroTouristResponseDTO.java
  src/main/java/com/seohaeng/backend/domain/place/dto/tourapiResponseDTO/DetailRepeatResponseDTO.java
  src/main/java/com/seohaeng/backend/domain/place/entity/place/Place.java
  src/main/java/com/seohaeng/backend/domain/place/entity/place/PlaceImage.java
  src/main/java/com/seohaeng/backend/domain/place/entity/placeAttribute/BookStoreAttribute.java
  src/main/java/com/seohaeng/backend/domain/place/entity/placeAttribute/FestivalAttribute.java
  src/main/java/com/seohaeng/backend/domain/place/entity/placeAttribute/RestaurantAttribute.java
  src/main/java/com/seohaeng/backend/domain/place/entity/placeAttribute/TouristSpotAttribute.java
  src/main/java/com/seohaeng/backend/domain/place/repository/PlaceImageRepository.java
  src/main/java/com/seohaeng/backend/domain/place/repository/PlaceRepository.java
  src/main/java/com/seohaeng/backend/domain/place/repository/attribute/BookStoreAttributeRepository.java
  src/main/java/com/seohaeng/backend/domain/place/repository/attribute/FestivalAttributeRepository.java
  src/main/java/com/seohaeng/backend/domain/place/repository/attribute/RestaurantAttributeRepository.java
  src/main/java/com/seohaeng/backend/domain/place/repository/attribute/TouristSpotAttributeRepository.java
  src/main/java/com/seohaeng/backend/domain/place/service/BookStoreAttributeService.java
  src/main/java/com/seohaeng/backend/domain/place/service/PipelineService.java
  src/main/java/com/seohaeng/backend/domain/place/service/PlaceQueryService.java
  src/main/java/com/seohaeng/backend/domain/place/util/PipelineScheduler.java
  src/main/java/com/seohaeng/backend/domain/place/util/TourApiClient.java
  src/main/java/com/seohaeng/backend/domain/readingSpot/controller/ReadingSpotController.java
  src/main/java/com/seohaeng/backend/domain/readingSpot/repository/ReadingSpotRepository.java
  src/main/java/com/seohaeng/backend/domain/readingSpot/service/ReadingSpotQueryService.java
  src/main/java/com/seohaeng/backend/domain/travelCourse/converter/StampConverter.java
  src/main/java/com/seohaeng/backend/domain/travelCourse/dto/StampResponseDTO.java
  src/main/java/com/seohaeng/backend/domain/travelCourse/entity/Region.java
  src/main/java/com/seohaeng/backend/domain/travelCourse/service/StampQueryService.java
  src/main/resources/application.yml
Labels: ✨ feature, ♻️ refactor

#49 ✨[Feat] 마커 클릭 시 하단 모달 조회 API 구현
  src/main/java/com/seohaeng/backend/domain/place/controller/PlaceInfoController.java
  src/main/java/com/seohaeng/backend/domain/place/controller/PlaceMarkerController.java
  src/main/java/com/seohaeng/backend/domain/place/dto/PlaceInfoDTO.java
  src/main/java/com/seohaeng/backend/domain/place/entity/place/Place.java
  src/main/java/com/seohaeng/backend/domain/place/repository/PlaceRepository.java
  src/main/java/com/seohaeng/backend/domain/place/service/PlaceInfoService.java
Labels: enhancement

#53 ✨[Feat] 약관 동의 로직 추가
  src/main/java/com/seohaeng/backend/domain/user/controller/UserController.java
  src/main/java/com/seohaeng/backend/domain/user/converter/UserConverter.java
  src/main/java/com/seohaeng/backend/domain/user/dto/UserRequestDTO.java
  src/main/java/com/seohaeng/backend/domain/user/dto/UserResponseDTO.java
  src/main/java/com/seohaeng/backend/domain/user/entity/Agreement.java
  src/main/java/com/seohaeng/backend/domain/user/entity/User.java
  src/main/java/com/seohaeng/backend/domain/user/repository/AgreementRepository.java
  src/main/java/com/seohaeng/backend/domain/user/service/UserCommandService.java
  src/main/java/com/seohaeng/backend/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨ feature, ♻️ refactor

#54 ♻️[Refactor] 공간책갈피 조회 API 인기순 정렬 옵션 추가
  src/main/java/com/seohaeng/backend/domain/place/util/PipelineRunner.java
  src/main/java/com/seohaeng/backend/domain/readingSpot/controller/ReadingSpotController.java
  src/main/java/com/seohaeng/backend/domain/readingSpot/service/ReadingSpotQueryService.java
Labels: ♻️ refactor

#61 ✨[Feat] 상세정보 조회 API 구현
  src/main/java/com/seohaeng/backend/domain/place/controller/PlaceController.java
  src/main/java/com/seohaeng/backend/domain/place/converter/PlaceConverter.java
  src/main/java/com/seohaeng/backend/domain/place/dto/PlaceResponseDTO.java
  src/main/java/com/seohaeng/backend/domain/place/repository/PlaceRepository.java
  src/main/java/com/seohaeng/backend/domain/place/service/PlaceQueryService.java
  src/main/java/com/seohaeng/backend/domain/review/repository/ReviewRepository.java
Labels: ✨ feature

#66 ♻️[Refactor] 공간책갈피 마커 조회 로직 변경
  src/main/java/com/seohaeng/backend/domain/place/controller/PlaceMarkerController.java
  src/main/java/com/seohaeng/backend/domain/place/service/BookStoreAttributeService.java
Labels: 🐛 bug

#68 ✨[Feat] 찜한 장소 조회 API 구현
  src/main/java/com/seohaeng/backend/domain/place/controller/PlaceController.java
  src/main/java/com/seohaeng/backend/domain/place/converter/PlaceConverter.java
  src/main/java/com/seohaeng/backend/domain/place/repository/SavedPlaceRepository.java
  src/main/java/com/seohaeng/backend/domain/place/service/PlaceQueryService.java
Labels: ✨ feature
