Repository SeoHaeng/SeoHaeng_BE, pull requests merged in 2025-07, with the labels that each got.

#11 [Feat] 책 검색, 북챌린지 이벤트 서점 조회 API 구현
  build.gradle
  src/main/java/com/seohaeng/backend/domain/bookChallenge/entity/BookChallengeProof.java
  src/main/java/com/seohaeng/backend/domain/bookChallenge/entity/BookChallengeProofComment.java
  src/main/java/com/seohaeng/backend/domain/bookChallenge/entity/BookChallengeProofImage.java
  src/main/java/com/seohaeng/backend/domain/bookChallenge/entity/BookChallengeProofLike.java
  src/main/java/com/seohaeng/backend/domain/bookChallenge/service/BookChallengeCommandService.java
  src/main/java/com/seohaeng/backend/domain/common/controller/CommonController.java
  src/main/java/com/seohaeng/backend/domain/common/converter/CommonConverter.java
  src/main/java/com/seohaeng/backend/domain/common/dto/BookSearchResponseDTO.java
  src/main/java/com/seohaeng/backend/domain/common/dto/CommonResponseDTO.java
  src/main/java/com/seohaeng/backend/domain/common/entity/BaseEntity.java
  src/main/java/com/seohaeng/backend/domain/common/service/CommonCommandService.java
  src/main/java/com/seohaeng/backend/domain/common/service/CommonQueryService.java
  src/main/java/com/seohaeng/backend/domain/notification/entity/Notification.java
  src/main/java/com/seohaeng/backend/domain/place/controller/PlaceController.java
  src/main/java/com/seohaeng/backend/domain/place/converter/PlaceConverter.java
  src/main/java/com/seohaeng/backend/domain/place/dto/PlaceResponseDTO.java
  src/main/java/com/seohaeng/backend/domain/place/entity/Place.java
  src/main/java/com/seohaeng/backend/domain/place/entity/PlaceEvent.java
  src/main/java/com/seohaeng/backend/domain/place/entity/PlaceType.java
  src/main/java/com/seohaeng/backend/domain/place/entity/Review.java
  src/main/java/com/seohaeng/backend/domain/place/entity/SavedPlace.java
  src/main/java/com/seohaeng/backend/domain/place/entity/repository/PlaceRepository.java
  src/main/java/com/seohaeng/backend/domain/place/repository/PlaceRepository.java
  src/main/java/com/seohaeng/backend/domain/place/service/PlaceQueryService.java
  src/main/java/com/seohaeng/backend/domain/readingSpot/entity/ReadingSpot.java
  src/main/java/com/seohaeng/backend/domain/readingSpot/entity/ReadingSpotComment.java
  src/main/java/com/seohaeng/backend/domain/travelCourse/entity/Stamp.java
  src/main/java/com/seohaeng/backend/domain/travelCourse/entity/TravelCourse.java
  src/main/java/com/seohaeng/backend/domain/travelCourse/entity/TravelCourseSchedule.java
  src/main/java/com/seohaeng/backend/domain/user/entity/LoginInfo.java
  src/main/java/com/seohaeng/backend/domain/user/entity/User.java
  src/main/java/com/seohaeng/backend/global/apiPayload/exception/ExceptionAdvice.java
  src/main/java/com/seohaeng/backend/global/configuration/RestTemplateConfig.java
  src/main/resources/application.yml
Labels: ✨ feature

#20 [Chore] docker compose 옵션 수정
  .github/workflows/deploy-dev.yml
Labels: 🐛 bug

#21 [Feat, Bug] 스탬프 시스템 구현, 경로 문제 해결
  src/main/java/com/seohaeng/backend/domain/travelCourse/controller/StampController.java
  src/main/java/com/seohaeng/backend/domain/travelCourse/controller/TravelCourseController.java
  src/main/java/com/seohaeng/backend/domain/travelCourse/converter/StampConverter.java
  src/main/java/com/seohaeng/backend/domain/travelCourse/converter/TravelCourseConverter.java
  src/main/java/com/seohaeng/backend/domain/travelCourse/dto/StampResponseDTO.java
  src/main/java/com/seohaeng/backend/domain/travelCourse/dto/TravelCourseResponseDTO.java
  src/main/java/com/seohaeng/backend/domain/travelCourse/entity/Region.java
  src/main/java/com/seohaeng/backend/domain/travelCourse/entity/Stamp.java
  src/main/java/com/seohaeng/backend/domain/travelCourse/entity/TravelCourseRegion.java
  src/main/java/com/seohaeng/backend/domain/travelCourse/repository/RegionRepository.java
  src/main/java/com/seohaeng/backend/domain/travelCourse/repository/StampRepository.java
  src/main/java/com/seohaeng/backend/domain/travelCourse/repository/TravelCourseRepository.java
  src/main/java/com/seohaeng/backend/domain/travelCourse/service/StampCommandService.java
  src/main/java/com/seohaeng/backend/domain/travelCourse/service/StampQueryService.java
  src/main/java/com/seohaeng/backend/domain/travelCourse/service/TravelCourseCommandService.java
  src/main/java/com/seohaeng/backend/domain/travelCourse/service/TravelCourseQueryService.java
  src/main/java/com/seohaeng/backend/domain/user/repository/UserRepository.java
  src/main/resources/application.yml
Labels: 🐛 bug, ✨ feature
